version: '4.21.1'
services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - 6379:6379

  app:  
    build: .
    volumes:
      - .:/summarizer
    image: summarizer
    container_name: summary_container
    command: fastapi run
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app