version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - 6379:6379
 
  db:  
    image: mysql:latest 
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: 'summarizer'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      
  app:  
    build: .
    volumes:
      - .:/summarizer
    image: summarizer
    ports:
      - 8000:8000
    container_name: summary_container
    command: fastapi run
    depends_on:
      - redis
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  db-data: