name: Docker Image CI

on:
  push:
    branches: [ "master" ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build and run Docker Compose
      run: |
        docker-compose up -d
    
    - name: Wait for services to be ready
      run: sleep 15
        
    - name: Check running containers
      run: docker ps
      
    - name: API test for /check endpoint
      run: |
        response=$(curl -s http://localhost/check)
        echo "$response"

    - name: Stop containers
      run: docker-compose down
