name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build and run Docker Compose
      run: |
        docker-compose up --build -d    
      
    - name: List all containers and exit codes
      run: docker ps -a --format "table {{.Names}}\t{{.Status}}"
      
    - name: API test for /check endpoint
      run: |
        for attempt in {1..5}; do
          response=$(curl -s http://localhost/check)
          if [ -n "$response" ]; then
            echo "$response"
            break
          else
            echo "Attempt $attempt failed, retrying in 5 seconds..."
            sleep 5
          fi
        done

    - name: Stop containers
      run: docker-compose down