name: Docker Image CI

on:
  push:
    branches: [ "master" ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build and run Docker Compose
      run: |
        docker-compose up --build -d
    
    - name: Wait for services and check health
      run: |
        attempt=1
        max_attempts=10
        until docker ps --format '{{.Names}}' | grep -q summary_container || [ $attempt -eq $max_attempts ]
        do
          echo "Attempt $attempt: Waiting for summary_container to be ready..."
          docker ps -a
          sleep 10
          attempt=$((attempt+1))
        done
    
        if [ $attempt -eq $max_attempts ]; then
          echo "summary_container failed to start. Dumping logs:"
          docker logs summary_container
          exit 1
        fi
        
    - name: Check running containers
      run: docker ps -a
      
    - name: API test for /check endpoint
      run: |
        response=$(curl http://localhost/check)
        echo "$response"

    - name: Stop containers
      run: docker-compose down
